### ISSUE TITLE
Use Leaflet-Geoman instead of Leaflet-Draw

### ISSUE THREAD

**Issue by Falke-Design** [RomanistHere/Measureland#2]
There is are more modern Draw-Tool [Leaflet-Geoman](https://github.com/geoman-io/leaflet-geoman) maybe you want to implement it. But is your decision, I only want to get you the information 😄

**Comment by RomanistHere** [comment]
yeah, I'll fix it. Thing is, I've already migrated the app to SvelteKit and it's in master, but I haven't released it yet, so it would be a lie. But thanks for the reminder, I will note it myself :)
